// flow-typed signature: 2f51e45ec84b88142af1044b61192af4
// flow-typed version: <<STUB>>/bde_v^1.2.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bde'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bde' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bde/client/bridge' {
  declare module.exports: any;
}

declare module 'bde/lib/report-error' {
  declare module.exports: any;
}

declare module 'bde/lib/require-module' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bde/client/bridge.js' {
  declare module.exports: $Exports<'bde/client/bridge'>;
}
declare module 'bde/index' {
  declare module.exports: $Exports<'bde'>;
}
declare module 'bde/index.js' {
  declare module.exports: $Exports<'bde'>;
}
declare module 'bde/lib/report-error.js' {
  declare module.exports: $Exports<'bde/lib/report-error'>;
}
declare module 'bde/lib/require-module.js' {
  declare module.exports: $Exports<'bde/lib/require-module'>;
}
