// flow-typed signature: 4e44299a9bdbadc04e4c270ac04f733f
// flow-typed version: <<STUB>>/fast-deep-equal_v^1.0.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fast-deep-equal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fast-deep-equal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fast-deep-equal/benchmark/index' {
  declare module.exports: any;
}

declare module 'fast-deep-equal/spec/index.spec' {
  declare module.exports: any;
}

declare module 'fast-deep-equal/spec/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fast-deep-equal/benchmark/index.js' {
  declare module.exports: $Exports<'fast-deep-equal/benchmark/index'>;
}
declare module 'fast-deep-equal/index' {
  declare module.exports: $Exports<'fast-deep-equal'>;
}
declare module 'fast-deep-equal/index.js' {
  declare module.exports: $Exports<'fast-deep-equal'>;
}
declare module 'fast-deep-equal/spec/index.spec.js' {
  declare module.exports: $Exports<'fast-deep-equal/spec/index.spec'>;
}
declare module 'fast-deep-equal/spec/tests.js' {
  declare module.exports: $Exports<'fast-deep-equal/spec/tests'>;
}
