// flow-typed signature: 00b2ace13a83c062756efdf723ea2a46
// flow-typed version: <<STUB>>/pull-with-latest_v^3.0.1/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pull-with-latest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pull-with-latest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'pull-with-latest/index' {
  declare module.exports: $Exports<'pull-with-latest'>;
}
declare module 'pull-with-latest/index.js' {
  declare module.exports: $Exports<'pull-with-latest'>;
}
