// flow-typed signature: a1b980d475df530a42ad552171b3d241
// flow-typed version: <<STUB>>/pull-tap_v^1.1.1/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pull-tap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pull-tap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pull-tap/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pull-tap/index' {
  declare module.exports: $Exports<'pull-tap'>;
}
declare module 'pull-tap/index.js' {
  declare module.exports: $Exports<'pull-tap'>;
}
declare module 'pull-tap/index.spec.js' {
  declare module.exports: $Exports<'pull-tap/index.spec'>;
}
