// flow-typed signature: 9aa5d635d43cd4292ed080b6d1c1071f
// flow-typed version: <<STUB>>/unflowify_v^1.0.1/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'unflowify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'unflowify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'unflowify/test/expected' {
  declare module.exports: any;
}

declare module 'unflowify/test/source' {
  declare module.exports: any;
}

// Filename aliases
declare module 'unflowify/index' {
  declare module.exports: $Exports<'unflowify'>;
}
declare module 'unflowify/index.js' {
  declare module.exports: $Exports<'unflowify'>;
}
declare module 'unflowify/test/expected.js' {
  declare module.exports: $Exports<'unflowify/test/expected'>;
}
declare module 'unflowify/test/source.js' {
  declare module.exports: $Exports<'unflowify/test/source'>;
}
